module.exports = {
  apps: [
    {
      name: "backend-3000",
      script: "src/server.js",
      instances: 1,
      exec_mode: "fork", 
      env: {
        PORT: 3000,
        NODE_ENV: "production",
      },
      max_memory_restart: "500M", 
      error_file: "./logs/err-3000.log",
      out_file: "./logs/out-3000.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      listen_timeout: 10000,
      kill_timeout: 5000,
    },
    {
      name: "backend-3001",
      script: "src/server.js",
      instances: 1,
      exec_mode: "fork",
      env: {
        PORT: 3001,
        NODE_ENV: "production",
      },
      max_memory_restart: "500M",
      error_file: "./logs/err-3001.log",
      out_file: "./logs/out-3001.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      listen_timeout: 10000,
      kill_timeout: 5000,
    },
    {
      name: "backend-3002",
      script: "src/server.js",
      instances: 1,
      exec_mode: "fork",
      env: {
        PORT: 3002,
        NODE_ENV: "production",
      },
      max_memory_restart: "500M",
      error_file: "./logs/err-3002.log",
      out_file: "./logs/out-3002.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      listen_timeout: 10000,
      kill_timeout: 5000,
    },
  ],
};
